/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Produto;
import model.bean.Vendedor;
import model.dao.ProdutoDAO;
import model.dao.VendedorDAO;
/**
 *
 */
public class Cad_Vendedor extends javax.swing.JFrame {

    
    public Cad_Vendedor() {
        initComponents();
        setSize(707, 570);
        this.setLocationRelativeTo(null);
        
        DefaultTableModel modelo = (DefaultTableModel) jtVendedor.getModel();
        jtVendedor.setRowSorter(new TableRowSorter(modelo));

        readJTable();
    }
    
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) jtVendedor.getModel();
        modelo.setNumRows(0);
        VendedorDAO vdao = new VendedorDAO();

        for (Vendedor v : vdao.read()) {

            modelo.addRow(new Object[]{
                v.getCodigo(),
                v.getNome(),
                v.getSal(),
            });
        }
    }
    public void readJTableForDesc(String desc) {
        
        DefaultTableModel modelo = (DefaultTableModel) jtVendedor.getModel();
        modelo.setNumRows(0);
        VendedorDAO vdao = new VendedorDAO();

        for (Vendedor v : vdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                v.getCodigo(),
                v.getNome(),
                v.getSal(),        
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_Cod_Ven = new javax.swing.JLabel();
        lbl_Nome_Ven = new javax.swing.JLabel();
        lbl_Salario_Fixo = new javax.swing.JLabel();
        txtCV = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtSal = new javax.swing.JTextField();
        lbl_IMG_Vendedor = new javax.swing.JLabel();
        btn_Fechar = new javax.swing.JButton();
        btn_Cadastrar_Ven = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btn_Limpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Vendedor");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_Cod_Ven.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_Cod_Ven.setText("Codigo do vendedor:");

        lbl_Nome_Ven.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_Nome_Ven.setText("Nome do Vendedor:");

        lbl_Salario_Fixo.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        lbl_Salario_Fixo.setText("Salario");

        txtSal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSalFocusLost(evt);
            }
        });

        lbl_IMG_Vendedor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_IMG_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trabalho/img/user.png"))); // NOI18N

        btn_Fechar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_Fechar.setText("Fechar");
        btn_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FecharActionPerformed(evt);
            }
        });

        btn_Cadastrar_Ven.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_Cadastrar_Ven.setText("Cadastrar");
        btn_Cadastrar_Ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Cadastrar_VenActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btn_Limpar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_Cod_Ven)
                                    .addGap(77, 77, 77)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbl_Nome_Ven, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(42, 42, 42))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_Cadastrar_Ven, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCV, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(268, 268, 268))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btn_Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Salario_Fixo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbl_IMG_Vendedor)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cod_Ven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Nome_Ven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Salario_Fixo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Cadastrar_Ven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar)
                            .addComponent(btnDeletar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(106, 106, 106))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_IMG_Vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(41, Short.MAX_VALUE))))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 330);

        jtVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Vendedor", "Nome Vendedor", "Salário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtVendedor);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 330, 710, 240);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FecharActionPerformed
        new Menu().setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_FecharActionPerformed

    private void btn_Cadastrar_VenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Cadastrar_VenActionPerformed
        Vendedor v = new Vendedor();
        VendedorDAO dao = new VendedorDAO();
        
        v.setCodigo(Integer.parseInt(txtCV.getText()));
        v.setNome(txtNome.getText());
        v.setSal(Double.parseDouble(txtSal.getText()));
        dao.create(v);

        txtCV.setText("");
        txtSal.setText("");
        txtNome.setText("");

        readJTable();
// TODO add your handling code here:
    }//GEN-LAST:event_btn_Cadastrar_VenActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
       txtCV.setText("");
       txtSal.setText("");
       txtNome.setText("");
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void txtSalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSalFocusLost
     
    }//GEN-LAST:event_txtSalFocusLost

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
         if (jtVendedor.getSelectedRow() != -1) {

            Vendedor v = new Vendedor();
            VendedorDAO dao = new VendedorDAO();

            v.setCodigo(Integer.parseInt(txtCV.getText()));
            v.setNome(txtNome.getText());
            v.setSal(Double.parseDouble(txtSal.getText()));
            dao.update(v);

            txtCV.setText("");
            txtSal.setText("");
            txtNome.setText("");
            readJTable();      
    }//GEN-LAST:event_btnAlterarActionPerformed
}
    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        if (jtVendedor.getSelectedRow() != -1) {

            Vendedor v = new Vendedor();
            VendedorDAO dao = new VendedorDAO();

            v.setCodigo((int) jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 0));
            
            dao.delete(v);

            txtCV.setText("");
            txtSal.setText("");
            txtNome.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto para excluir.");
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void jtVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendedorMouseClicked
        if (jtVendedor.getSelectedRow() != -1) {

            txtCV.setText(jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 0).toString());
            txtNome.setText(jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 1).toString());
            txtSal.setText(jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_jtVendedorMouseClicked
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cad_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cad_Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btn_Cadastrar_Ven;
    private javax.swing.JButton btn_Fechar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtVendedor;
    private javax.swing.JLabel lbl_Cod_Ven;
    private javax.swing.JLabel lbl_IMG_Vendedor;
    private javax.swing.JLabel lbl_Nome_Ven;
    private javax.swing.JLabel lbl_Salario_Fixo;
    private javax.swing.JTextField txtCV;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSal;
    // End of variables declaration//GEN-END:variables
}
